config/routes.rb
Rails.application.routes.draw do

  # Scope manages languages
  scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do

    # Devise
    devise_for :users

    # Private
    authenticate :user do
      resources :teams
      resources :users
      resources :meetings
    end

    # Roots
    root to: "welcomes#index"

    # Reroute bad links to home
    get "*path", to: "welcomes#index"

  end

  # Redirect to language
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join('|')})\/).*/}, format: false
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :team, optional: false

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 20 }

  validates :datetime, presence: true

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!


  # GET /teams
  def index
    @meetings = Meeting.order(:datetime)
  end

  # GET /admin/1
  def show
  end

  # GET /admin/new
  def new
    @meeting = Meeting.new
  end

  # GET /admin/1/edit
  def edit
  end

  # POST /meetings
  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to meeting_path(@meeting), notice: 'Meeting was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/1
  def update
    if @meeting.update(meeting_params)
      redirect_to meeting_path(@meeting), notice: 'Meeting was successfully edited.'
    else
      render :edit
    end
  end

  # DELETE /admin/1
  def destroy
    @meeting.destroy
    redirect_to meetings_path, notice: 'Meeting was successfully cancelled.'
  end

  private
    def get_meeting
      @meeting = Meeting.friendly.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:title, :description, :name, :datetime, :team_id)
    end
end

app/views/meetings/_form.haml
= simple_form_for @meeting do |f|
  - if @meeting.errors.any?
    #error_explanation
      - @meeting.errors.full_messages.each do |msg|
        .alert.alert-danger.alert-dismissible{:role => 'alert'}
          %button.close{'aria-label' => 'Close', 'data-dismiss' => 'alert', :type => 'button'}
            %span{'aria-hidden' => 'true'} ×
          %b Error:
          = msg
  .row
    %h5 Meeting
    .field
      = f.label :title
      = f.text_field :title, class: 'form-control', autofocus: true
    .field
      = f.label :description
      = f.text_area :description, class: 'form-control'
    .field
      = f.label :"Date & Time"
      = f.datetime_select :datetime, class: 'form-control'
    .field
      = f.label :team
      = f.collection_select :team_id, Team.all, :id, :name, class: 'form-control'


  %hr
  = f.submit 'Save', class: 'btn btn-sm btn-primary btn-block'

app/views/meetings/edit.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to meetings_path(team_id: @team), class: 'nav-link' do
        %i.mdi.mdi-calendar
        = t('shared.navbar.meetings')
    %li.nav-item
      = link_to meeting_path(@meeting), class: 'nav-link' do
        = @meeting.description
    %li.nav-item
      .nav-link Edit
  %ul.nav.navbar-nav.pull-sm-right
    %li.nav-item
      = link_to 'Cancel', meetings_path(team_id: @team), class: 'nav-link'
%hr
= render partial: 'form'

app/views/meetings/index.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      .nav-link
        %i.mdi.mdi-calendar
        = t('shared.navbar.meetings')
  %ul.nav.navbar-nav.pull-sm-right
    %li.nav-item
      = link_to content_tag(:i, '', class:'mdi mdi-calendar') + ' New', new_meeting_path, class: 'nav-link'
%hr
.row
  - @meetings.each do |meeting|
    .col-sm-4
      .card{id: dom_id(meeting)}
        .card-block
          = link_to meeting.title, meeting_path(meeting), style: "color:##{team.color}"
          %br
          = meeting.description
          %br = meeting.datetime

app/views/meetings/new.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to meetings_path, class: 'nav-link' do
        %i.mdi.mdi-calendar
        = t('shared.navbar.meetings')
    %li.nav-item
      .nav-link
        %i.mdi.mdi-calendar-plus
        New
  %ul.nav.navbar-nav.pull-sm-right
    %li.nav-item
      = link_to 'Cancel', meetings_path, class: 'nav-link'
%hr
= render 'form'

app/views/meetings/show.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to meetings_path(team_id: @team), class: 'nav-link' do
        %i.mdi.mdi-calendar
        = t('shared.navbar.meetings')
    %li.nav-item
      .nav-link
        = @meeting.title
  %ul.nav.navbar-nav.pull-sm-right
    %li.nav-item
      = link_to 'Edit', edit_meeting_path(@meeting), class: 'nav-link'
    %li.nav-item
      = link_to 'Delete', meeting_path(@meeting), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'nav-link text-danger'
%hr
%h1
  = @meeting.title
.row
  .col-sm-10.offset-sm-2
    %dl
      %dt Description
      %dd= @meeting.description
      %dt Date & Time
      %dd= @meeting.datetime