config/routes.rb
Rails.application.routes.draw do

  # Scope manages languages
  scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do

    # Devise
    devise_for :users

    # Private
    authenticate :user do
      resources :teams
      resources :users
      resources :meetings
    end

    # Roots
    root to: "welcomes#index"

    # Reroute bad links to home
    get "*path", to: "welcomes#index"

  end

  # Redirect to language
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join('|')})\/).*/}, format: false
end

app/models/user.rb
class User < ApplicationRecord
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :team_users, dependent: :destroy
  has_many :teams, through: :team_users

  def team_list
    self.teams
  end

  def admin?(team)
    self.team_users.where(team: team, admin: true).present?
  end

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :get_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:email)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_path(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'User was successfully edited.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'User was successfully deleted.'
  end

  private
    def get_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :get_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:email)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was successfully edited.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully deleted.'
  end

  private
    def get_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:first_name, :last_name, :time_zone, :email, :password, :password_confirmation, :avatar)
    end
end

app/views/users/_form.haml
= simple_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      - @user.errors.full_messages.each do |msg|
        .alert.alert-danger= msg

  = f.input :first_name, class: 'form-control', autofocus: true
  = f.input :last_name, class: 'form-control'
  = f.input :time_zone, required: true
  = f.input :email, class: 'form-control'
  = f.input :password, class: 'form-control'
  = f.input :password_confirmation, class: 'form-control'
  %hr
  = f.submit 'Save', class: 'btn btn-sm btn-primary btn-block'

app/views/users/edit.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to users_path(team_id: @team), class: 'nav-link' do
        %i.mdi.mdi-account
        = t('shared.navbar.users')
    %li.nav-item
      = link_to user_path(@user), class: 'nav-link' do
        = @user.first_name
        = @user.last_name
    %li.nav-item
      .nav-link Edit
  %ul.nav.navbar-nav.pull-sm-right
    %li.nav-item
      = link_to 'Cancel', users_path(team_id: @team), class: 'nav-link'
%hr
= render partial: 'form'

app/views/users/index.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      .nav-link
        %i.mdi.mdi-account
        = t('shared.navbar.users')
  %ul.nav.navbar-nav.pull-sm-right
    %li.nav-item
      = link_to content_tag(:i, '', class:'mdi mdi-account-plus') + ' Add', new_user_path, class: 'nav-link text-success'
%hr
.row
  - @users.each do |user|
    .col-sm-4
      .card{id: dom_id(user)}
        .card-block
          = link_to user_path(user) do
            = image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", class: 'avatar avatar-inline'
            = user.first_name
            = user.last_name
            %span.tag.tag-primary= Time.current.in_time_zone(user.time_zone).strftime('%Z')

app/views/users/new.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to users_path(team_id: @team), class: 'nav-link' do
        %i.mdi.mdi-account
        = t('shared.navbar.users')
    %li.nav-item
      .nav-link
        %i.mdi.mdi-account-plus
        Add
  %ul.nav.navbar-nav.pull-sm-right
    %li.nav-item
      = link_to 'Cancel', users_path(team_id: @team), class: 'nav-link'
%hr
= render partial: 'form'

app/views/users/show.haml
%nav.navbar.navbar-fixed-top
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to users_path(team_id: @team), class: 'nav-link' do
        %i.mdi.mdi-account
        = t('shared.navbar.users')
    %li.nav-item
      .nav-link
        = @user.first_name
        = @user.last_name
  %ul.nav.navbar-nav.pull-sm-right
    - if current_user == @user
      %li.nav-item
        = link_to 'Edit', edit_user_path(@user), class: 'nav-link'
      %li.nav-item
        = link_to 'Delete', user_path(@user), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'nav-link text-danger'
%hr
%h1
  = image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email)}", class: 'avatar avatar-inline'
  = @user.first_name
  = @user.last_name
.row
  .col-sm-10.offset-sm-2
    %dl
      %dt Timezone
      %dd
        %span.tag.tag-primary= Time.current.in_time_zone(@user.time_zone).strftime("%H:%M")
        = @user.time_zone
      %dt Email
      %dd= @user.email
.row
  - @user.teams.each do |team|
    .col-sm-4
      .card{id: dom_id(team)}
        .card-block
          = link_to team.name, team_path(team), style: "color:##{team.color}"
          %br
          = team.description