config/routes.rb
Rails.application.routes.draw do

  # Scope manages languages
  scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do

    # Devise
    devise_for :users

    # Private
    authenticate :user do
      resources :teams
      resources :users
      resources :meetings
    end

    # Roots
    root to: "welcomes#index"

    # Reroute bad links to home
    get "*path", to: "welcomes#index"

  end

  # Redirect to language
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join('|')})\/).*/}, format: false
end

app/views/shared/_flash.haml
- if flash
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      .alert.alert-default.animated.fadeInDown.delay.col-sm-6.offset-sm-3#flash{class: "alert-#{name == 'notice' ? 'info' : 'success'}"}
        %a.close{'data-dismiss' => 'alert'}
          &times;
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/shared/_footer.haml
%footer
  .container-fluid.m-t-3.m-b-1
    .row
      .col-sm-6
        %small Copyright © 2016 Superpencil Ltd.
      .col-sm-6
        .pull-sm-right
          %a{href: "http://www.superpencil.com/?utm_source=timegiver&utm_medium=footer+link&utm_campaign=project", class: 'superpencil', alt: 'Superpencil'}
            %small Design and Development by
            %b.tag.tag-secondary
              = image_tag 'superpencil.svg', alt: 'Superpencil'
              Superpencil

app/views/shared/_hour.haml
- hour = hour + script_time
- if hour > 23
  - hour = hour - 24
- if script_time == hour
  .hour.active-time><= hour
- elsif (9..17).include?(hour)
  - if hour == 9
    .hour.work-time.first><= hour
  - elsif hour == 17
    .hour.work-time.last><= hour
  - else
    .hour.work-time><= hour
- elsif (7..22).include?(hour)
  .hour.awake-time><= hour
- else
  .hour><= hour

app/views/shared/_navbar.haml
%nav.navbar.navbar-left
  %ul.nav.navbar-nav
    %li.nav-item
      = link_to root_url, class: 'nav-link' do
        %span.mdi.mdi-timer-sand-empty
        .popside Home

    - if user_signed_in?
      %li.nav-item
        = link_to teams_path, class: 'nav-link' do
          %span.mdi.mdi-account-multiple
          .popside= t('.teams')
      %li.nav-item
        = link_to users_path, class: 'nav-link' do
          %span.mdi.mdi-account
          .popside= t('.users')

      %li.nav-item
        = link_to meetings_path, class: 'nav-link' do
          %span.mdi.mdi-calendar
          .popside= t('.meetings')

      %li.nav-item
        = link_to edit_user_registration_path, class: 'nav-link' do
          %span.mdi.mdi-account-circle
          .popside= t('devise.registrations.edit.title', resource: current_user.model_name.human)

      %li.nav-item
        = link_to destroy_user_session_path, method: :delete, class: 'nav-link' do
          %span.mdi.mdi-logout-variant
          .popside= t('.sign_out')

    - else
      %li.nav-item
        = link_to new_user_session_path, class: 'nav-link' do
          %span.mdi.mdi-login-variant
          .popside= t('devise.shared.links.sign_in')

      %li.nav-item
        = link_to new_user_registration_path, class: 'nav-link' do
          %span.mdi.mdi-pen
          .popside= t('devise.shared.links.sign_up')

      %li.nav-item
        .dropdown
          %button.btn.btn-sm.btn-secondary#languageDropdown.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :type => 'button'}
            %i.mdi.mdi-translate
          .dropdown-menu.dropdown-menu-right{'aria-labelledby' => 'languageDropdown'}
            - I18n.available_locales.each do |lan|
              = link_to t('language', locale: lan), current_path_new_locale(lan.to_sym), class: 'dropdown-item'

app/views/shared/_timegiver.haml
#timegiver.card-block
  - @team.users.each do |user|
    - time = Time.current.in_time_zone(user.time_zone)
    - script_time = time.hour
    - readable_time = time.strftime("%H:%M")
    .row{class: current_user == user ? 'current_user' : nil }
      .col-xs-3
        = link_to user do
          = user.first_name
          = user.last_name
          - if user.admin?(@team)
            %i.mdi.mdi-star
        %span.tag.tag-primary= time.strftime('%Z')
      .col-xs-9
        .timebar
          .line.bar
            - (0..23).drop(13).each do |hour|
              = render partial: 'shared/hour', locals: {hour: hour, time: time, script_time: script_time, readable_time: readable_time}
            - (0..23).first(13).each do |hour|
              = render partial: 'shared/hour', locals: {hour: hour, time: time, script_time: script_time, readable_time: readable_time}

app/views/shared/_timelines.haml
.timelines
  - @team.users.each do |user|
    - time = Time.current.in_time_zone(user.time_zone)
    - script_time = time.hour
    - readable_time = time.strftime("%H:%M")
    .row{class: current_user == user ? 'current_user' : nil }
      .col-md-2
        = link_to user do
          = image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", class: 'avatar avatar-inline'
          = user.first_name
      .col-md-10
        .timebar
          .line.bar
            - (0..23).drop(13).each do |hour|
              = render partial: 'shared/hour', locals: {hour: hour, time: time, script_time: script_time, readable_time: readable_time}
            - (0..23).first(13).each do |hour|
              = render partial: 'shared/hour', locals: {hour: hour, time: time, script_time: script_time, readable_time: readable_time}